//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Desktop.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvonManager.Desktop.Assets.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch Löschen des Artikels werden auch alle Varianten gelöscht..
        /// </summary>
        internal static string DeleteArtikel {
            get {
                return ResourceManager.GetString("DeleteArtikel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch Löschen des Heftes werden alle Zuordnungen zu Kunden entfernt..
        /// </summary>
        internal static string DeleteHeft {
            get {
                return ResourceManager.GetString("DeleteHeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn es noch Bestellungen zum Kunden gibt, wird ein Fehler ausgelöst!.
        /// </summary>
        internal static string DeleteKunde {
            get {
                return ResourceManager.GetString("DeleteKunde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch Löschen einer Markierung werden alle Verknüpfungen mit Artikel entfernt..
        /// </summary>
        internal static string DeleteMarkierung {
            get {
                return ResourceManager.GetString("DeleteMarkierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch Löschen einer Serie werden auch alle Zuordnungen zu Artikeln entfernt!.
        /// </summary>
        internal static string DeleteSerie {
            get {
                return ResourceManager.GetString("DeleteSerie", resourceCulture);
            }
        }
    }
}
