//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public Artikel()
        {
            this.Varianten = new HashSet<ArtikelVarianten>();
            this.Kategorien = new HashSet<Kategorien>();
            this.Markierungen = new HashSet<Markierungen>();
        }
    
        public int ArtikelId { get; set; }
        public string Artikelname { get; set; }
        public string Artikelbeschreibung { get; set; }
        public string ArtikelNr { get; set; }
        public string Inhalt { get; set; }
        public Nullable<decimal> Einzelpreis { get; set; }
        public Nullable<int> Lagerbestand { get; set; }
        public Nullable<int> SerienId { get; set; }
        public byte[] Bild { get; set; }
    
        public virtual Serien Serien { get; set; }
        public virtual ICollection<ArtikelVarianten> Varianten { get; set; }
        public virtual ICollection<Kategorien> Kategorien { get; set; }
        public virtual ICollection<Markierungen> Markierungen { get; set; }
    }
}
