//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvDBaseEntities : DbContext
    {
        public AvDBaseEntities()
            : base("name=AvDBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikel> Artikels { get; set; }
        public DbSet<ArtikelVarianten> ArtikelVariantens { get; set; }
        public DbSet<Bestelldetail> Bestelldetails { get; set; }
        public DbSet<Bestellstatus> Bestellstatus { get; set; }
        public DbSet<Bestellung> Bestellungs { get; set; }
        public DbSet<Entitaeten> Entitaetens { get; set; }
        public DbSet<Hefte> Heftes { get; set; }
        public DbSet<Hefte_x_Kunden> Hefte_x_Kunden { get; set; }
        public DbSet<Kategorien> Kategoriens { get; set; }
        public DbSet<Kunden> Kundens { get; set; }
        public DbSet<Markierungen> Markierungens { get; set; }
        public DbSet<Serien> Seriens { get; set; }
    }
}
