//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelldetail
    {
        public int DetailId { get; set; }
        public int BestellId { get; set; }
        public string Campagne { get; set; }
        public Nullable<int> Jahr { get; set; }
        public Nullable<int> Seite { get; set; }
        public string ArtikelNr { get; set; }
        public Nullable<int> Menge { get; set; }
        public string Artikelbeschr { get; set; }
        public string FGD { get; set; }
        public Nullable<decimal> Einzelpreis { get; set; }
    
        public virtual Bestellung Bestellung { get; set; }
    }
}
