//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellung
    {
        public Bestellung()
        {
            this.Bestelldetails = new HashSet<Bestelldetail>();
        }
    
        public int BestellId { get; set; }
        public Nullable<int> KundenId { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> Loeschvormerkung { get; set; }
    
        public virtual ICollection<Bestelldetail> Bestelldetails { get; set; }
        public virtual Bestellstatus Bestellstatus { get; set; }
        public virtual Kunden Kunden { get; set; }
    }
}
