//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entitaeten
    {
        public Entitaeten()
        {
            this.Markierungens = new HashSet<Markierungen>();
        }
    
        public int EntitaetId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Markierungen> Markierungens { get; set; }
    }
}
