//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hefte
    {
        public Hefte()
        {
            this.Hefte_x_Kunden = new HashSet<Hefte_x_Kunden>();
        }
    
        public int HeftId { get; set; }
        public string Titel { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> Jahr { get; set; }
        public byte[] Bild { get; set; }
    
        public virtual ICollection<Hefte_x_Kunden> Hefte_x_Kunden { get; set; }
    }
}
