//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hefte_x_Kunden
    {
        public int HeftId { get; set; }
        public int KundenId { get; set; }
        public Nullable<System.DateTime> Erhalten { get; set; }
        public Nullable<bool> HatBestellt { get; set; }
    
        public virtual Hefte Hefte { get; set; }
        public virtual Kunden Kunden { get; set; }
    }
}
