//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markierungen
    {
        public Markierungen()
        {
            this.Artikels = new HashSet<Artikel>();
        }
    
        public int MarkierungId { get; set; }
        public int EntitaetId { get; set; }
        public string Titel { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> FarbeARGB { get; set; }
    
        public virtual Entitaeten Entitaeten { get; set; }
        public virtual ICollection<Artikel> Artikels { get; set; }
    }
}
